spring:
  application:
    name: stayease
  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: on_param
      include-exception: false

server:
  port: 8080

# CORS Configuration
cors:
  allowed-origins: http://localhost:4200
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS,PATCH
  allowed-headers: "*"
  exposed-headers: Authorization,Link,X-Total-Count
  allow-credentials: true
  max-age: 3600
